# Generated by Django 4.0.3 on 2022-04-16 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('youtubeapp', '0006_alter_video_options_remove_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonologuePhotoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='monologue/')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_photos', to='youtubeapp.channel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'фото для монолога',
                'verbose_name_plural': 'Фотки монологов',
            },
        ),
        migrations.CreateModel(
            name='MonologuePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monologues', to='youtubeapp.channel', verbose_name='Канал')),
                ('images', models.ManyToManyField(null=True, to='monologue.monologuephotocontent', verbose_name='Фотки')),
            ],
            options={
                'verbose_name': 'Монолог',
                'verbose_name_plural': 'Монологи',
            },
        ),
    ]
