# Generated by Django 4.0.3 on 2022-04-04 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import youtubeapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('slug', models.SlugField(verbose_name='URL для категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название канала')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone_photo', models.ImageField(blank=True, null=True, upload_to='phone_photos/')),
                ('slug', models.SlugField(max_length=200, verbose_name='URL для канала')),
                ('description', models.TextField(verbose_name='Описание канала')),
                ('categories', models.ManyToManyField(blank=True, to='youtubeapp.category', verbose_name='Категории канала')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=youtubeapp.models.channel_directory, verbose_name='Видео файл')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtubeapp.channel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Видео файл',
                'verbose_name_plural': 'Видео файлы',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название ролика')),
                ('description', models.TextField(verbose_name='Описание')),
                ('visibility', models.BooleanField(choices=[(False, 'Приватный'), (True, 'Публичный')])),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('video_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='youtubeapp.videofile', verbose_name='Видео-файл')),
            ],
            options={
                'verbose_name': 'Видео-ролик',
                'verbose_name_plural': 'Видео-ролики',
            },
        ),
    ]
