# Generated by Django 4.0.3 on 2022-04-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0004_video_likes_video_views_subscribe_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео-файл'),
        ),
        migrations.DeleteModel(
            name='VideoFile',
        ),
    ]
