# Generated by Django 4.0.3 on 2022-04-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0005_alter_video_video_file_delete_videofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created'], 'verbose_name': 'Видео-ролик', 'verbose_name_plural': 'Видео-ролики'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
